BookShopCourseWork/Models/AuthorController/AddAuthor.cs
namespace BookShopCourseWork.Models.AuthorController
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using System.ComponentModel.DataAnnotations;

    public class AddAuthor
    {
        [Required]
        [MinLength(2, ErrorMessage = "Author first name must be minimum 2 symbols!")]
        [MaxLength(25, ErrorMessage = "Author first name must be maximum 25 symbols!")]
        [Display(Name = "First name")]
        public string FirstName {get; set;}

        [Required]
        [MinLength(2, ErrorMessage = "Author last name must be minimum 2 symbols!")]
        [MaxLength(25, ErrorMessage = "Author last name must be maximum 25 symbols!")]
        [Display(Name = "Last name")]
        public string LastName {get; set;}
    }
}

BookShopCourseWork/Models/AuthorController/DeleteAuthor.cs
namespace BookShopCourseWork.Models.AuthorController
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using System.ComponentModel.DataAnnotations;

    public class DeleteAuthor
    {
        [Required]
        public int AuthorId {get; set;}
       
    }
}

BookShopCourseWork/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using System.Threading.Tasks;
using BookShopCourseWork.Models;
using BookShopCourseWork.Models.AuthorController;
using BookShopCourseWork.Services.Interfaces;
using BookShopCourseWork.Services;
using BookShopCourseWork.ViewModels;
using Microsoft.AspNetCore.Http;
using System.Net;

namespace BookShopCourseWork.Controllers
{
    [Authorize(Policy = "adminOnly")]
    [Route("~/Author")]
    public class AuthorController : Controller
    {
        private IAuthorService authorService { get; set; }
        public AuthorController()
        {
            authorService = new AuthorService();
        }
        [HttpPost("AddAuthor")]
        public IActionResult AddAuthor(AddAuthor author)
        {
            if (ModelState.IsValid)
            {
                bool status = authorService.AddAuthor(author);
                if (status)
                {
                    return RedirectToAction("Success", "Admin", new { message = "AddAuthor" });
                }
                else
                {
                    return RedirectToAction("Failed", "Admin", new { message = "AddAuthor" });
                }
            }
            else
            {
                return BadRequest();
            }
        }
        [HttpPost("DeleteAuthor")]
        public IActionResult DeleteAuthor(DeleteAuthor author)
        {
            if (ModelState.IsValid)
            {
                bool status = authorService.DeleteAuthor(author);
                if (status)
                {
                    return RedirectToAction("Success", "Admin", new { message = "DeleteAuthor" });
                }
                else
                {
                    return RedirectToAction("Failed", "Admin", new { message = "DeleteAuthor" });
                }
            }
            else
            {
                return BadRequest();
            }
        }
        [HttpPost("UpdateAuthorBook")]
        public IActionResult UpdateAuthorBook(UpdateAuthorBook authorBook)
        {
            if (ModelState.IsValid)
            {
                bool status = authorService.UpdateAuthorBook(authorBook);
                if (authorBook.Operation == "addAuthor")
                {
                    if (status)
                    {
                        return RedirectToAction("Success", "Admin", new { message = "BookAuthorConnected" });
                    }
                    else
                    {
                        return RedirectToAction("Failed", "Admin", new { message = "BookAuthorConnected" });
                    }
                }
                else if (authorBook.Operation == "removeAuthor")
                {
                    if (status)
                    {
                        return RedirectToAction("Success", "Admin", new { message = "BookAuthorDisconnected" });
                    }
                    else
                    {
                        return RedirectToAction("Failed", "Admin", new { message = "BookAuthorDisconnected" });
                    }
                }
                else
                {
                    return BadRequest();
                }
            }
            else
            {
                return BadRequest();
            }
        }

    }
}

BookShopCourseWork/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using BookShopCourseWork.Extensions;
using System.Collections.Generic;
using System.Linq;
using BookShopCourseWork.Models.AdminController;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using BookShopCourseWork.Models;
using BookShopCourseWork.Models.BookController;
using BookShopCourseWork.Services.Interfaces;
using BookShopCourseWork.Services;
using BookShopCourseWork.ViewModels;
using Microsoft.AspNetCore.Http;
using System.Net;

namespace BookShopCourseWork.Controllers
{
    [Route("~/Book")]
    public class BookController : Controller
    {
        private IBookService bookService { get; set; }

        private IGenreService genreService { get; set; }
        private IAuthorService authorService { get; set; }
        public BookController()
        {
            bookService = new BookService();
            genreService = new GenreService();
            authorService = new AuthorService();
        }
        [HttpGet("{id}")]
        public IActionResult Index([FromRoute] int id)
        {
            if (id != 0)
            {
                Book book = bookService.GetBookById(id);
                if (book == null)
                {
                    return NotFound();
                }
                else
                {
                    return View(book);
                }
            }
            else
            {
                return NotFound();
            }
        }

        [HttpGet("GetBookByIdJson/{id}")]
        public IActionResult GetBookByIdJson([FromRoute] int id)
        {
            if (id != 0)
            {
                Book book = bookService.GetBookById(id);
                if (book == null)
                {
                    return NotFound();
                }
                else
                {
                    return Json(book);
                }
            }
            else
            {
                return NotFound();
            }
        }
        [HttpGet("ViewAllBooks")]
        public IActionResult ViewAllBooks([FromQuery] int page, [FromQuery] string order, [FromQuery] string search, [FromQuery] string authors, [FromQuery] string genres)
        {
            if(page==0)
            {
                return NotFound();
            }
            if(order==null)
            {
                return BadRequest();
            }
            List<Genre> genresList = genreService.GetAllGenres();
            List<Author> authorsList = authorService.GetAllAuthors();
            List<Book> books = bookService.GetAllBooks();
            if(search!=null)
            {
                books = books.Where(b=> b.Title.ToLower().Contains(search.ToLower())).ToList();
            }
            if(authors!=null)
            {
                List<int> authorsId = authors.Split(',').Select(Int32.Parse).ToList();
                books = books.Where(b => b.Authors.Any(a=> authorsId.Contains(a.Id))).ToList();
            }
            if(genres!=null)
            {
                List<int> genresId = genres.Split(',').Select(Int32.Parse).ToList();
                books = books.Where(b => b.Genres.Any(g=> genresId.Contains(g.Id))).ToList();
            }
            switch(order)
            {
                case "priceAscending":
                    books = books.OrderBy(b=>b.Price).ToList();
                break;
                case "priceDescending":
                    books = books.OrderByDescending(b=>b.Price).ToList();
                break;
                case "titleAscending":
                    books = books.OrderBy(b=>b.Title,  new AlphanumComparatorFast()).ToList();
                break;
                case "titleDescending":
                    books = books.OrderByDescending(b=>b.Title, new AlphanumComparatorFast()).ToList();
                break;
                case "publishAscending":
                    books = books.OrderBy(b=>b.Id).ToList();
                break;
                case "publishDescending":
                    books = books.OrderByDescending(b=>b.Id).ToList();
                break;
                case "releaseAscending":
                    books = books.OrderBy(b=>b.PublishedOn).ToList();
                break;
                case "releaseDescending":
                    books = books.OrderByDescending(b=>b.PublishedOn).ToList();
                break;
                default:
                return BadRequest();
            }
            int booksnum = page * 16;
            if(books.Count == 0)
            {
                return View(new ViewBooksModel() { NumberOfBooks = 0, Authors = authorsList, Genres = genresList});
            }
            if(booksnum>books.Count)
            {
                try
                {
                    if(books.Count-(booksnum-16) == 0)
                    {
                        return NotFound();
                    }
                    return View(new ViewBooksModel() { Books = books.GetRange(booksnum-16, books.Count-(booksnum-16)), NumberOfBooks = books.Count, Authors = authorsList, Genres = genresList});
                }
                catch
                {
                    return NotFound();
                }
            }
            return View(new ViewBooksModel() {Books = books.GetRange(booksnum-16, 16), NumberOfBooks = books.Count, Authors = authorsList, Genres = genresList});
        }
        [Authorize(Policy = "adminOnly")] 
        [HttpPost("EditBook")]
        public IActionResult EditBook(EditBook book)
        {
                if (ModelState.IsValid)
                {
                    bool status = bookService.EditBook(book);
                    if(status)
                    {
                        return RedirectToAction("Success", "Admin", new { message = "EditBook" });
                    }
                    else
                    {
                        return RedirectToAction("Failed", "Admin", new { message = "EditBook" });
                    }
                }
                else
                {
                    return BadRequest();
                }
        } 
        [Authorize(Policy = "adminOnly")] 
        [HttpPost("CreateBook")]
        public IActionResult CreateBook(CreateBook book)
        {
                if (ModelState.IsValid)
                {
                    bool status = bookService.CreateBook(book);
                    if(status)
                    {
                        return RedirectToAction("Success", "Admin", new { message = "CreateBook" });
                    }
                    else
                    {
                        return RedirectToAction("Failed", "Admin", new { message = "CreateBook" });
                    }
                }
                else
                {
                    return BadRequest();
                }
        }
    }
}

BookShopCourseWork/Controllers/GenreController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using BookShopCourseWork.Models;
using BookShopCourseWork.Models.GenreController;
using BookShopCourseWork.Services.Interfaces;
using BookShopCourseWork.Services;
using Microsoft.AspNetCore.Http;
using System.Net;

namespace BookShopCourseWork.Controllers
{
    [Authorize(Policy = "adminOnly")] 
    [Route("~/Genre")]
    public class GenreController : Controller
    {
        private IGenreService genreService { get; set; }
        public GenreController()
        {
            genreService = new GenreService();
        }
        [HttpPost("AddGenre")]
        public IActionResult AddGenre(AddGenre genre)
        {
            if(ModelState.IsValid)
            {
                bool status = genreService.AddGenre(genre);
                if (status)
                {
                    return RedirectToAction("Success", "Admin", new { message = "AddGenre" });
                }
                else
                {
                    return RedirectToAction("Failed", "Admin", new { message = "AddGenre" });
                }
            }
            else
            {
                return BadRequest();
            }
        }
        [HttpPost("DeleteGenre")]
        public IActionResult DeleteGenre(DeleteGenre genre)
        {
            if(ModelState.IsValid)
            {
                bool status = genreService.DeleteGenre(genre);
                if (status)
                {
                    return RedirectToAction("Success", "Admin", new { message = "DeleteGenre" });
                }
                else
                {
                    return RedirectToAction("Failed", "Admin", new { message = "DeleteGenre" });
                }
            }
            else
            {
                return BadRequest();
            }
        }
        [HttpPost("UpdateGenreBook")]
        public IActionResult UpdateGenreBook(UpdateGenreBook genreBook)
        {
            if(ModelState.IsValid)
            {
                bool status = genreService.UpdateGenreBook(genreBook);
                if (genreBook.Operation == "addGenre")
                {
                    if (status)
                    {
                        return RedirectToAction("Success", "Admin", new { message = "BookGenreConnected" });
                    }
                    else
                    {
                        return RedirectToAction("Failed", "Admin", new { message = "BookGenreConnected" });
                    }
                }
                else if (genreBook.Operation == "removeGenre")
                {
                    if (status)
                    {
                        return RedirectToAction("Success", "Admin", new { message = "BookGenreDisconnected" });
                    }
                    else
                    {
                        return RedirectToAction("Failed", "Admin", new { message = "BookGenreDisconnected" });
                    }
                }
                else
                {
                    return BadRequest();
                }
            }
            else
            {
                return BadRequest();
            }
        }

    }
}

BookShopCourseWork/Controllers/PublisherController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using System.Threading.Tasks;
using BookShopCourseWork.Models;
using BookShopCourseWork.Models.PublisherController;
using BookShopCourseWork.Services.Interfaces;
using BookShopCourseWork.Services;
using BookShopCourseWork.ViewModels;
using Microsoft.AspNetCore.Http;
using System.Net;

namespace BookShopCourseWork.Controllers
{
    [Authorize(Policy = "adminOnly")]
    public class PublisherController : Controller
    {
        private IPublisherService publisherService { get; set; }
        public PublisherController()
        {
            publisherService = new PublisherService();
        }
        [HttpPost("AddPublisher")]
        public IActionResult AddPublisher(AddPublisher publisher)
        {
            if(ModelState.IsValid)
            {
                bool status = publisherService.AddPublisher(publisher);
                if (status)
                {
                    return RedirectToAction("Success", "Admin", new { message = "AddPublisher" });
                }
                else
                {
                    return RedirectToAction("Failed", "Admin", new { message = "AddPublisher" });
                }
            }
            else
            {
                return BadRequest();
            }
        }
        [HttpPost("DeletePublisher")]
        public IActionResult DeletePublisher(DeletePublisher publisher)
        {
            if(ModelState.IsValid)
            {
                bool status = publisherService.DeletePublisher(publisher);
                if (status)
                {
                    return RedirectToAction("Success", "Admin", new { message = "DeletePublisher" });
                }
                else
                {
                    return RedirectToAction("Failed", "Admin", new { message = "DeletePublisher" });
                }
            }
            else
            {
                return BadRequest();
            }
        }
        [HttpPost("UpdatePublisherBook")]
        public IActionResult UpdatePublisherBook(UpdatePublisherBook publisherBook)
        {
            if(ModelState.IsValid)
            {
                bool status = publisherService.UpdatePublisherBook(publisherBook);
                if (status)
                {
                    return RedirectToAction("Success", "Admin", new { message = "BookPublisherConnected" });
                }
                else
                {
                    return RedirectToAction("Failed", "Admin", new { message = "BookPublisherConnected" });
                }
            }
            else
            {
                return BadRequest();
            }
        }
    }
}

BookShopCourseWork/Views/Admin/AddAuthor.cshtml
@using BookShopCourseWork.Models.AuthorController
@model AddAuthor
@{
    ViewData["ActivePage"] = "AddAuthor";
    ViewData["ActiveTab"] = "Authors";
}

<div class="mt-3 mr-3 ml-3 mb-3">
    <h4>Add author</h4>
    <hr>
    <div>
        <form asp-controller="Author" asp-action="AddAuthor">
            <div class="row">
                <div class="col">
                    <label asp-for="FirstName"></label>
                    <input type="text" class="form-control" asp-for="FirstName">
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="col">
                    <label asp-for="LastName"></label>
                    <input type="text" class="form-control" asp-for="LastName">
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col">
                    <button type="submit" class="btn btn-primary">Add author</button>
                </div>
            </div>
        </form>
    </div>
</div>

BookShopCourseWork/Views/Admin/AddGenre.cshtml
@{
    ViewData["ActivePage"] = "AddGenre";
    ViewData["ActiveTab"] = "Genres";
}
@using BookShopCourseWork.Models.GenreController
@model AddGenre
<div class="mt-3 mr-3 ml-3 mb-3">
    <h4>Add genre</h4>
    <hr>
    <form asp-controller="Genre" asp-action="AddGenre">
        <div class="row">
            <div class="col">
                <label asp-for="GenreName"></label>
                <input type="text" asp-for="GenreName" class="form-control">
                <span asp-validation-for="GenreName" class="text-danger"></span>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col">
                <button type="submit" class="btn btn-primary">Add genre</button>
            </div>
        </div>
    </form>
</div>

BookShopCourseWork/Views/Admin/AddPublisher.cshtml
@{
    ViewData["ActivePage"] = "AddPublisher";
    ViewData["ActiveTab"] = "Publishers";
}
@using BookShopCourseWork.Models.PublisherController
@model AddPublisher
<div class="mt-3 mr-3 ml-3 mb-3">
    <h4>Add publisher</h4>
    <hr>
    <form asp-controller="Publisher" asp-action="AddPublisher">
        <div class="row">
            <div class="col">
                <label asp-for="PublisherName"></label>
                <input type="text" asp-for="PublisherName" class="form-control">
                <span asp-validation-for="PublisherName" class="text-danger"></span>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col">
                <button type="submit" class="btn btn-primary">Add publisher</button>
            </div>
        </div>
    </form>
</div>

BookShopCourseWork/Views/Admin/CreateBook.cshtml
@{
    ViewData["ActivePage"] = "CreateBook";
    ViewData["ActiveTab"] = "Books";
}
@model BookShopCourseWork.Models.BookController.CreateBook;
<div class="mt-3 ml-3 mr-3 mb-3">
    <h4>Create book</h4>
    <hr>
    <form asp-controller="Book" asp-action="CreateBook">
        <div class="row">
            <div class="col">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" type="text" id="Title">
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="col">
                <label asp-for="Pages"></label>
                <input class="form-control" type="number" asp-for="Pages" step="1">
                <span asp-validation-for="Pages" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <label asp-for="Description"></label>
                <textarea class="form-control" asp-for="Description" style="resize: none;" rows="16" maxlength="3000"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <label asp-for="Price"></label>
                <input class="form-control" type="number" asp-for="Price" step="0.01">
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="col">
                <label asp-for="PublishedOn"></label>
                <input class="form-control" type="date" asp-for="PublishedOn">
                <span asp-validation-for="PublishedOn" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <label asp-for="GenreName"></label>
                <input class="form-control" type="text" asp-for="GenreName">
                <span asp-validation-for="GenreName" class="text-danger"></span>
            </div>
            <div class="col">
                <label asp-for="PublisherName"></label>
                <input class="form-control" type="text" asp-for="PublisherName">
                <span asp-validation-for="PublisherName" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <h5>Author</h5>
            <div class="col">
                <label asp-for="FirstName"></label>
                <input class="form-control" type="text" asp-for="FirstName">
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="col">
                <label asp-for="LastName"></label>
                <input class="form-control" type="text" asp-for="LastName">
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <label asp-for="ImgUrl"></label>
                <input class="form-control" type="text" asp-for="ImgUrl">
                <span asp-validation-for="ImgUrl" class="text-danger"></span>
            </div>
        </div>
        <button class="btn btn-primary mt-3" type="submit">Create book</button>
    </form>

</div>

BookShopCourseWork/Views/Admin/DeleteAuthor.cshtml
@using BookShopCourseWork.Models.AuthorController
@model DeleteAuthor
@{
    ViewData["ActiveTab"] = "Authors";
    ViewData["ActivePage"] = "DeleteAuthor";
}
<div class="mt-3 mb-3 ml-4 mr-3">
    <h4>Delete author</h4>
    <hr>
    <form asp-controller="Author" asp-action="DeleteAuthor">
        <div class="row">
            <div class="col">
                <label asp-for="AuthorId"></label>  
                <input type="number" class="form-control" asp-for="AuthorId">
                <span asp-validation-for="AuthorId" class="text-danger"></span>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col">
                <button type="submit" class="btn btn-primary">Delete author</button>
            </div>
        </div>
    </form>

</div>

BookShopCourseWork/Views/Admin/Failed.cshtml
@using BookShopCourseWork.Models.AdminController
@model Message
<div class="mt-3 ml-3 mr-3 mb-3 text-center">
    <h3>Failed!</h3>
    <p>@Model.MessageString</p>
</div>

BookShopCourseWork/Views/Admin/FindOrderById.cshtml
@model BookShopCourseWork.Models.BookController.EditBook;
@{
    ViewData["ActivePage"] = "FindOrderById";
    ViewData["ActiveTab"] = "Orders";
}
<div class="mt-3 mr-3 ml-3">
    <h4>Find order by Id</h4>
    <hr>
    <label for="id">Order Id</label>
    <input type="number" id="id" class="form-control">
    <button class="btn btn-primary mt-3" onclick="findOrder()">Find order</button>
</div>

BookShopCourseWork/Views/Admin/Success.cshtml
@using BookShopCourseWork.Models.AdminController
@model Message
<div class="mt-3 ml-3 mr-3 mb-3 text-center">
    <h3>Success!</h3>
    <p>@Model.MessageString</p>
</div>

BookShopCourseWork/Views/Admin/UpdateAuthorBook.cshtml
@{
    ViewData["ActivePage"] = "UpdateAuthorBook";
    ViewData["ActiveTab"] = "Authors";
}
@using BookShopCourseWork.Models.AuthorController
@model UpdateAuthorBook
<div class="mt-3 mr-3 ml-3">
    <h4>Add author and book</h4>
    <hr>
    <form asp-controller="Author" asp-action="UpdateAuthorBook">
        <div class="row">
            <div class="col">
                <label asp-for="BookId" ></label>
                <input type="text" asp-for="BookId" class="form-control">
                <span asp-validation-for="BookId" class="text-danger"></span>
            </div>
            <div class="col">
                <label asp-for="AuthorId" ></label>
                <input type="text" asp-for="AuthorId" class="form-control">
                <span asp-validation-for="AuthorId" class="text-danger"></span>
            </div>
        </div>
        <div class="row mt-3 mb-3">
            <div class="col">
                <label asp-for="Operation" ></label>
                <select type="text" asp-for="Operation" class="form-control">
                    <option value="addAuthor">Add author to book</option>
                    <option value="removeAuthor">Disconnect author and book</option>
                </select>
            </div>
            <div class="col">
                <button type="submit" class="btn btn-primary">Update author and book</button>
            </div>
        </div>        
    </form>

</div>

BookShopCourseWork/Views/Admin/ViewAllAuthors.cshtml
@using BookShopCourseWork.Models
@{
    ViewData["ActiveTab"] = "Authors";
    ViewData["ActivePage"] = "ViewAllAuthors";
}
@model List<Author>
<div class="mt-3 ml-3 mb-3 mr-3">
    <h4>View all authors</h4>
    <hr>
     <table class="table table-striped table-primary">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Author full name</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Author a in Model)
                {
                    <tr><td>@a.Id</td><td>@a.FirstName @a.LastName</td></tr>
                }
            </tbody>

        </table>
</div>

BookShopCourseWork/Views/Admin/ViewAllGenres.cshtml
@using BookShopCourseWork.Models
@{
    ViewData["ActiveTab"] = "Genres";
    ViewData["ActivePage"] = "ViewAllGenres";
}
@model List<Genre>
<div class="mt-3 ml-3 mb-3 mr-3">
    <h4>View all genres</h4>
    <hr>
     <table class="table table-striped table-primary">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Genre name</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Genre g in Model)
                {
                    <tr><td>@g.Id</td><td>@g.GenreName</td></tr>
                }
            </tbody>
        </table>
</div>

BookShopCourseWork/Views/Admin/ViewAllPublishers.cshtml
@using BookShopCourseWork.Models
@{
    ViewData["ActiveTab"] = "Publishers";
    ViewData["ActivePage"] = "ViewAllPublishers";
}
@model List<Publisher>
<div class="mt-3 ml-3 mb-3 mr-3">
    <h4>View all publishers</h4>
    <hr>
     <table class="table table-striped table-primary">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Publisher name</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Publisher p in Model)
                {
                    <tr><td>@p.Id</td><td>@p.PublisherName</td></tr>
                }
            </tbody>
        </table>
</div>

BookShopCourseWork/Views/Admin/ViewAndEditOrder.cshtml
@using BookShopCourseWork.Models.AdminController;
@using BookShopCourseWork.Extensions;
@using BookShopCourseWork.Models.Enums;
@using System;
@model OrderAndUserInfo;
@{
    ViewData["Title"] = "View order";
    ViewData["ActiveTab"] = "Orders";
}
<div class="container mt-3">
    <h4>№@Model.Order.Id</h4>
    <hr>
    <span class="fw-bold">First name: </span> @Model.FirstName<br>
    <span class="fw-bold">Last name: </span> @Model.LastName<br>
    <span class="fw-bold">Email: </span> @Model.Order.UserEmail<br>
    <span class="fw-bold">Address: </span> @Model.Order.Address<br>
    <span class="fw-bold">City: </span> @Model.Order.City<br>
    <span class="fw-bold">Notes: </span> @Model.Order.Notes<br>
    <span class="fw-bold">Date: </span> @Model.Order.Date<br>
    <span class="fw-bold">Status: </span>
    <select id="status" class="form-control">
        <option value="SENT">Sent</option>
        <option value="PROCESSING">Processing</option>
        <option value="DELIVERED">Delivered</option>
        <option value="CANCELLED">Cancelled</option>
    </select>
    <button type="submit" class="btn btn-primary mt-3" onclick="changeStatusOrder(@Model.Order.Id)">Change status</button>
    <script>
        document.getElementById("status").value = "@Model.Order.Status";
    </script>
    <div class="row mt-3">
        <table class="table table-striped table-primary">
            <thead>
                <tr>
                    <th scope="col">Title book</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Price</th>
                </tr>
            </thead>
            <tbody>
                @foreach (BookQuantity bq in @Model.Order.BookQuantities)
                {
                    <tr><td><a href="../../Book/@bq.Book.Id">@bq.Book.Title</a></td><td>@bq.Quantity</td><td>€ @((bq.Quantity*bq.Book.Price).ToString("0.00"))</td></tr>
                }
            </tbody>

        </table>
    </div>
    <div class="row">
        <div class="col">
            <p class="fw-bold fs-4">Total: € @Model.Order.Total</p>
        </div>
    </div>
</div>